# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deporte',
            name='urlImagen',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
